steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloud-run-01-321907/mydatacheck01', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloud-run-01-321907/mydatacheck01']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'datacheck01', '--image', 'gcr.io/cloud-run-01-321907/mydatacheck01', '--region', 'us-central1', '--platform', 'managed', '--port','80']
images:
- gcr.io/cloud-run-01-321907/mydatacheck01
